# -*- coding: utf-8 -*-
"""URL-Shortener.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3ll_LvQSPzTa2ynE4zvR8LGt-sqvoAq
"""

pip install pyshorteners

import pyshorteners as ps

url ="https://victorylytics.com/#Services/"

u = ps.Shortener().tinyurl.short(url)

print(u)

